version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./event_management.db
      - SECRET_KEY=your-secret-key-here-change-in-production
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend/event_management.db:/app/event_management.db
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: ./backend
    command: celery -A src.tasks worker --loglevel=info
    environment:
      - DATABASE_URL=sqlite:///./event_management.db
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend/event_management.db:/app/event_management.db
    depends_on:
      - redis
      - backend